# This config file is set up to -

# execute scripts on your local machine in Chrome browser in desktop mode and default resolution:

configuration.profiles=web/desktop/chrome


# pick up suite related properties from 'demo' suite folder:

configuration.suites=demo

# pick up environment related properties from 'EPAM.Nuzhnenko' environment folder:

configuration.environments=EPAM.Nuzhnenko

ui.wait.timeout=PT90S
web.alert.wait-for-alert-timeout=PT2S
scenario.fail-fast=true
